import { generateQuestion, generateChoices, pickBattleAnimals, makeBattleViewModel, presenceHasOpponent, pickWelcomeContent } from './game-logic.js';

const SUPABASE_URL='https://lzjehqfmvzsmramndooq.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_OQR1t7L94Vo9aqhySYTTFA_QbfLfU5w';
const CLIENT_TOKEN_KEY='sequence_battle_client_token';
const OPPONENT_GRACE_MS=5000;
const HOST_HEARTBEAT_INTERVAL_MS=3000;
const LOBBY_EXPIRY_PADDING_MS=150;
const JOIN_PROBE_TIMEOUT_MS=2000;
const VICTORY_MESSAGES=['🏆 王者誕生！等差數列霸主就是你！','⚡ 完美制霸！這局完全被你掌控！','👑 冠軍登場！你的數列火力無人能擋！'];
const DEFEAT_MESSAGES=['差一點就反殺了！下一局再來！','這局只是熱身，下局一定扳回來！','已經很接近了，再挑戰一次！'];

const screens={login:document.getElementById('login-screen'),lobby:document.getElementById('lobby-screen'),waiting:document.getElementById('waiting-screen'),matched:document.getElementById('matched-screen'),battle:document.getElementById('battle-screen')};
const nicknameForm=document.getElementById('nickname-form'),nicknameInput=document.getElementById('nickname-input'),enterLobbyBtn=document.getElementById('enter-lobby-btn'),welcomeAnimal=document.getElementById('welcome-animal'),welcomePhrase=document.getElementById('welcome-phrase'),currentNicknameEl=document.getElementById('current-nickname'),roomsList=document.getElementById('rooms-list'),refreshLobbyBtn=document.getElementById('refresh-lobby-btn'),createRoomBtn=document.getElementById('create-room-btn'),waitingHostName=document.getElementById('waiting-host-name'),cancelRoomBtn=document.getElementById('cancel-room-btn'),matchedPlayer1=document.getElementById('matched-player1'),matchedPlayer2=document.getElementById('matched-player2'),messageBar=document.getElementById('message-bar'),connectionPill=document.getElementById('connection-pill'),connectionText=document.getElementById('connection-text');
const techArena=document.getElementById('tech-arena'),selfName=document.getElementById('self-name'),opponentName=document.getElementById('opponent-name'),selfHp=document.getElementById('self-hp'),opponentHp=document.getElementById('opponent-hp'),selfAnimal=document.getElementById('self-animal'),opponentAnimal=document.getElementById('opponent-animal'),selfAnimalName=document.getElementById('self-animal-name'),opponentAnimalName=document.getElementById('opponent-animal-name'),selfScore=document.getElementById('self-score'),opponentScore=document.getElementById('opponent-score'),questionType=document.getElementById('question-type'),battleQuestion=document.getElementById('battle-question'),choiceGrid=document.getElementById('choice-grid'),battleFeedback=document.getElementById('battle-feedback'),battleResult=document.getElementById('battle-result'),battleResultTitle=document.getElementById('battle-result-title'),battleResultText=document.getElementById('battle-result-text'),battleReturnBtn=document.getElementById('battle-return-btn'),petalLayer=document.getElementById('petal-layer'),battleStatusText=document.getElementById('battle-status-text'),laserLeft=document.getElementById('laser-left'),laserRight=document.getElementById('laser-right'),swordLeft=document.getElementById('sword-left'),swordRight=document.getElementById('sword-right'),disconnectOverlay=document.getElementById('disconnect-overlay'),disconnectCountdown=document.getElementById('disconnect-countdown');

let supabaseClient=null,nickname='',currentScreen='login',currentRoomId=null,currentSeat=null,lobbyChannel=null,gameChannel=null,busy=false,currentQuestion=null,lastEventId=0,latestGameState=null,battleStarted=false;
let opponentWasPresent=false,opponentMissingTimer=null,disconnectReturnTimer=null,disconnectCountdownTimer=null,disconnectHandled=false;
let hostHeartbeatTimer=null,lobbyExpiryTimer=null;

function randomFrom(items){return items[Math.floor(Math.random()*items.length)]}
function clearPetalRain(){petalLayer.textContent=''}
function launchPetalRain(durationMs=5000){clearPetalRain();if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const icons=['🌸','🌺','✨'];for(let i=0;i<70;i+=1){const petal=document.createElement('span');petal.className='petal';petal.textContent=icons[i%icons.length];petal.style.left=`${Math.random()*100}%`;petal.style.animationDelay=`${Math.random()*1.2}s`;petal.style.animationDuration=`${2.8+Math.random()*2}s`;petalLayer.appendChild(petal)}setTimeout(clearPetalRain,durationMs+1500)}
function renderStartWelcome(){const{animal,phrase}=pickWelcomeContent();welcomeAnimal.textContent=animal.emoji;welcomePhrase.textContent=phrase}
function fallbackUuid(){const bytes=new Uint8Array(16);crypto.getRandomValues(bytes);bytes[6]=(bytes[6]&15)|64;bytes[8]=(bytes[8]&63)|128;const hex=[...bytes].map(b=>b.toString(16).padStart(2,'0'));return `${hex.slice(0,4).join('')}-${hex.slice(4,6).join('')}-${hex.slice(6,8).join('')}-${hex.slice(8,10).join('')}-${hex.slice(10,16).join('')}`}
function makeProbeId(){return typeof crypto.randomUUID==='function'?crypto.randomUUID():fallbackUuid()}
function getClientToken(){let token=localStorage.getItem(CLIENT_TOKEN_KEY);if(!token){token=typeof crypto.randomUUID==='function'?crypto.randomUUID():fallbackUuid();localStorage.setItem(CLIENT_TOKEN_KEY,token)}return token}
function setScreen(name){Object.entries(screens).forEach(([key,el])=>el.classList.toggle('active',key===name));currentScreen=name;document.body.classList.toggle('battle-mode',name==='battle');window.scrollTo({top:0,behavior:'smooth'})}
function showMessage(text='',tone='neutral'){messageBar.textContent=text;messageBar.dataset.tone=tone}
function setConnectionStatus(text,tone='neutral'){connectionText.textContent=text;connectionPill.dataset.tone=tone}
function setBusy(value){busy=value;createRoomBtn.disabled=value;refreshLobbyBtn.disabled=value;document.querySelectorAll('.join-btn').forEach(button=>button.disabled=value)}
function normalizedNickname(value){return value.trim()}
function nicknameIsValid(value){const clean=normalizedNickname(value);const length=Array.from(clean).length;return length>=1&&length<=20}
function friendlyError(error,fallback='發生連線問題，請稍後再試。'){const raw=String(error?.message||error||'');if(raw.includes('ROOM_ALREADY_FULL'))return'這個房間剛剛已被其他同學加入，請選另一個房間。';if(raw.includes('ROOM_NOT_FOUND'))return'這個房間已經不存在，正在重新整理大廳。';if(raw.includes('HOST_OFFLINE'))return'房主已離開，請選其他房間。';if(raw.includes('GAME_NOT_PLAYING'))return'本局已經結束。';if(raw.includes('Failed to fetch')||raw.includes('NetworkError'))return'目前無法連上 Supabase，請檢查網路後再試。';return raw?`${fallback}（${raw}）`:fallback}
function normalizeRpcData(data){return Array.isArray(data)?data[0]:data}
async function removeChannel(channel){if(channel&&supabaseClient){try{await supabaseClient.removeChannel(channel)}catch(error){console.warn('Remove channel failed:',error)}}}
function clearPresenceTimers(){clearTimeout(opponentMissingTimer);clearTimeout(disconnectReturnTimer);clearInterval(disconnectCountdownTimer);opponentMissingTimer=null;disconnectReturnTimer=null;disconnectCountdownTimer=null}
function resetRoundFlags(){clearPresenceTimers();opponentWasPresent=false;disconnectHandled=false;disconnectOverlay.classList.remove('show');battleResult.classList.remove('show','victory','defeat');clearPetalRain();battleStatusText.textContent='對戰中'}

function stopHostHeartbeat(){clearInterval(hostHeartbeatTimer);hostHeartbeatTimer=null}
function clearLobbyExpiryRefresh(){clearTimeout(lobbyExpiryTimer);lobbyExpiryTimer=null}
function scheduleLobbyExpiryRefresh(rooms){clearLobbyExpiryRefresh();const ttls=(rooms||[]).map(room=>Number(room?.expires_in_ms)).filter(value=>Number.isFinite(value)&&value>=0);if(!ttls.length||currentScreen!=='lobby')return;const delay=Math.max(250,Math.min(...ttls)+LOBBY_EXPIRY_PADDING_MS);lobbyExpiryTimer=setTimeout(()=>{lobbyExpiryTimer=null;if(currentScreen==='lobby')loadLobby()},delay)}
async function sendHostHeartbeat(){if(!supabaseClient||currentSeat!==1||currentScreen!=='waiting'||!currentRoomId)return;const{error}=await supabaseClient.rpc('heartbeat_room',{p_room_id:currentRoomId,p_client_token:getClientToken()});if(error&&!String(error?.message||error).includes('ROOM_ALREADY_STARTED'))console.warn('Host heartbeat failed:',error)}
function startHostHeartbeat(){stopHostHeartbeat();if(currentSeat!==1||currentScreen!=='waiting'||!currentRoomId)return;void sendHostHeartbeat();hostHeartbeatTimer=setInterval(()=>void sendHostHeartbeat(),HOST_HEARTBEAT_INTERVAL_MS)}

async function loadLobby(){if(!supabaseClient||currentScreen!=='lobby')return;roomsList.setAttribute('aria-busy','true');roomsList.innerHTML='<div class="empty-state">正在取得等待中的房間…</div>';const{data,error}=await supabaseClient.rpc('list_live_rooms');roomsList.setAttribute('aria-busy','false');if(error){clearLobbyExpiryRefresh();roomsList.innerHTML='<div class="empty-state">目前讀不到遊戲大廳，請按重新整理再試。</div>';showMessage(friendlyError(error,'遊戲大廳讀取失敗。'),'bad');return}const rooms=Array.isArray(data)?data:[];renderRooms(rooms);scheduleLobbyExpiryRefresh(rooms)}
function renderRooms(rooms){roomsList.textContent='';if(!rooms.length){roomsList.innerHTML='<div class="empty-state"><span class="emoji">🏕️</span>目前沒有等待中的房間。你可以成為第一個建立房間的人！</div>';return}rooms.forEach(room=>{const card=document.createElement('article');card.className='room-card';const top=document.createElement('div');top.className='room-card-top';const host=document.createElement('div');host.className='room-host';const strong=document.createElement('strong');strong.textContent=`${room.host_nickname} 的房間`;const small=document.createElement('small');small.textContent='等待對手加入';host.append(strong,small);const count=document.createElement('span');count.className='player-count';count.textContent=`${room.player_count||1}/2`;top.append(host,count);const button=document.createElement('button');button.className='join-btn';button.type='button';button.textContent='加入對戰';button.addEventListener('click',()=>joinRoom(room.id));card.append(top,button);roomsList.appendChild(card)})}
async function subscribeLobby(){await removeChannel(lobbyChannel);if(!supabaseClient)return;lobbyChannel=supabaseClient.channel(`lobby-${getClientToken()}`).on('postgres_changes',{event:'*',schema:'public',table:'rooms'},()=>{if(currentScreen==='lobby')loadLobby()}).subscribe(status=>{if(status==='SUBSCRIBED')setConnectionStatus('大廳即時連線中','good');if(status==='CHANNEL_ERROR'||status==='TIMED_OUT')setConnectionStatus('即時連線異常','bad')})}
async function enterLobby(){stopHostHeartbeat();clearLobbyExpiryRefresh();currentRoomId=null;currentSeat=null;latestGameState=null;lastEventId=0;battleStarted=false;currentQuestion=null;resetRoundFlags();await removeChannel(gameChannel);gameChannel=null;currentNicknameEl.textContent=nickname;setScreen('lobby');showMessage('');await subscribeLobby();await loadLobby()}
async function returnToInitial(){stopHostHeartbeat();clearLobbyExpiryRefresh();clearPresenceTimers();await removeChannel(gameChannel);gameChannel=null;await removeChannel(lobbyChannel);lobbyChannel=null;currentRoomId=null;currentSeat=null;latestGameState=null;lastEventId=0;battleStarted=false;currentQuestion=null;nickname='';nicknameInput.value='';cancelRoomBtn.hidden=true;disconnectOverlay.classList.remove('show');renderStartWelcome();setScreen('login');showMessage('');setConnectionStatus('資料庫已連接','good');nicknameInput.focus()}

async function createRoom(){if(busy||!supabaseClient)return;setBusy(true);showMessage('正在建立房間…');try{const{data,error}=await supabaseClient.rpc('create_room',{p_nickname:nickname,p_client_token:getClientToken()});if(error)throw error;const result=normalizeRpcData(data);if(!result?.success||!result?.room_id)throw new Error('建立房間時沒有取得 room_id');currentRoomId=result.room_id;currentSeat=result.seat||1;resetRoundFlags();cancelRoomBtn.hidden=false;waitingHostName.textContent=`${nickname} 的房間`;await removeChannel(lobbyChannel);lobbyChannel=null;setScreen('waiting');startHostHeartbeat();showMessage('房間已公開到遊戲大廳，等待另一位同學加入。','good');await watchGameState(currentRoomId)}catch(error){showMessage(friendlyError(error,'建立房間失敗。'),'bad')}finally{setBusy(false)}}
async function confirmHostOnline(roomId){if(!supabaseClient||!roomId)return false;const probeId=makeProbeId();const channel=supabaseClient.channel(`game-${roomId}`);return await new Promise(resolve=>{let settled=false;let timeoutId=null;const finish=async result=>{if(settled)return;settled=true;clearTimeout(timeoutId);try{await removeChannel(channel)}finally{resolve(result)}};channel.on('broadcast',{event:'host_ack'},({payload})=>{if(payload?.probe_id===probeId)void finish(true)}).subscribe(async status=>{if(status==='SUBSCRIBED'){timeoutId=setTimeout(()=>void finish(false),JOIN_PROBE_TIMEOUT_MS);const response=await channel.send({type:'broadcast',event:'join_probe',payload:{probe_id:probeId}});if(response!=='ok'&&response!=='timed out')console.warn('Join probe send result:',response)}if(status==='CHANNEL_ERROR'||status==='TIMED_OUT'||status==='CLOSED')void finish(false)})})}
async function joinRoom(roomId){if(busy||!supabaseClient)return;setBusy(true);try{showMessage('正在確認房主在線…');const hostOnline=await confirmHostOnline(roomId);if(!hostOnline){showMessage('房主已離開，請選其他房間。','bad');setScreen('lobby');await subscribeLobby();await loadLobby();return}showMessage('房主在線，正在加入房間…','good');const{data,error}=await supabaseClient.rpc('join_room',{p_room_id:roomId,p_nickname:nickname,p_client_token:getClientToken()});if(error)throw error;const result=normalizeRpcData(data);if(!result?.success||!result?.room_id)throw new Error('加入房間時沒有取得 room_id');currentRoomId=result.room_id;currentSeat=result.seat||2;resetRoundFlags();cancelRoomBtn.hidden=true;await removeChannel(lobbyChannel);lobbyChannel=null;setScreen('waiting');await watchGameState(currentRoomId)}catch(error){showMessage(friendlyError(error,'加入房間失敗。'),'bad');setScreen('lobby');await subscribeLobby();await loadLobby()}finally{setBusy(false)}}
async function cancelCurrentRoom(){if(!supabaseClient||!currentRoomId||currentSeat!==1)return;cancelRoomBtn.disabled=true;showMessage('正在取消房間…');try{const{data,error}=await supabaseClient.rpc('cancel_room',{p_room_id:currentRoomId,p_client_token:getClientToken()});if(error)throw error;const result=normalizeRpcData(data);if(!result?.success)throw new Error('取消房間失敗');await enterLobby();showMessage('房間已取消。','good')}catch(error){if(String(error?.message||error).includes('ROOM_ALREADY_STARTED')){showMessage('對手已加入，對戰即將開始。','good');await fetchGameState(currentRoomId)}else{showMessage(friendlyError(error,'取消房間失敗。'),'bad')}}finally{cancelRoomBtn.disabled=false}}

async function fetchGameState(roomId){if(!supabaseClient||!roomId)return;const{data,error}=await supabaseClient.from('game_state').select('room_id,status,player1_name,player2_name,player1_hp,player2_hp,player1_score,player2_score,winner_seat,last_event_id,last_event_type,last_event_seat,started_at,finished_at').eq('room_id',roomId).maybeSingle();if(error){showMessage(friendlyError(error,'讀取對戰狀態失敗。'),'bad');return}if(data)handleGameState(data)}
function handlePresenceSync(){if(!gameChannel||!currentSeat)return;const hasOpponent=presenceHasOpponent(gameChannel.presenceState(),currentSeat);if(hasOpponent){opponentWasPresent=true;clearTimeout(opponentMissingTimer);opponentMissingTimer=null;return}if(!opponentWasPresent||!battleStarted||latestGameState?.status!=='playing'||disconnectHandled)return;if(!opponentMissingTimer){opponentMissingTimer=setTimeout(()=>{opponentMissingTimer=null;const stillMissing=gameChannel&&!presenceHasOpponent(gameChannel.presenceState(),currentSeat);if(stillMissing)handleOpponentDisconnected()},OPPONENT_GRACE_MS)}}
function handleOpponentDisconnected(){if(disconnectHandled||latestGameState?.status!=='playing')return;disconnectHandled=true;document.querySelectorAll('.choice-btn').forEach(button=>button.disabled=true);battleStatusText.textContent='對手斷線';disconnectOverlay.classList.add('show');let seconds=3;disconnectCountdown.textContent=`${seconds} 秒後回到遊戲初始`;disconnectCountdownTimer=setInterval(()=>{seconds-=1;disconnectCountdown.textContent=seconds>0?`${seconds} 秒後回到遊戲初始`:'正在回到遊戲初始…'},1000);disconnectReturnTimer=setTimeout(()=>returnToInitial(),3200)}
async function watchGameState(roomId){await removeChannel(gameChannel);if(!supabaseClient)return;const channel=supabaseClient.channel(`game-${roomId}`,{config:{presence:{key:getClientToken()}}});gameChannel=channel;channel.on('postgres_changes',{event:'UPDATE',schema:'public',table:'game_state',filter:`room_id=eq.${roomId}`},payload=>handleGameState(payload.new)).on('broadcast',{event:'join_probe'},({payload})=>{if(currentRoomId!==roomId||currentSeat!==1||currentScreen!=='waiting'||!payload?.probe_id)return;void channel.send({type:'broadcast',event:'host_ack',payload:{probe_id:payload.probe_id}})}).on('presence',{event:'sync'},handlePresenceSync).on('presence',{event:'join'},handlePresenceSync).on('presence',{event:'leave'},handlePresenceSync).subscribe(async status=>{if(status==='SUBSCRIBED'){setConnectionStatus('房間即時連線中','good');await channel.track({seat:currentSeat,nickname,online_at:new Date().toISOString()});await fetchGameState(roomId);handlePresenceSync()}if(status==='CHANNEL_ERROR'||status==='TIMED_OUT')setConnectionStatus('房間即時連線異常','bad')});await fetchGameState(roomId)}

function renderHearts(el,hp){el.textContent='';for(let i=0;i<7;i+=1){const heart=document.createElement('span');heart.className=`heart${i<hp?'':' lost'}`;heart.textContent='♥';el.appendChild(heart)}}
function setupAnimals(){const[seat1Animal,seat2Animal]=pickBattleAnimals(currentRoomId);const selfChoice=currentSeat===2?seat2Animal:seat1Animal;const opponentChoice=currentSeat===2?seat1Animal:seat2Animal;selfAnimal.textContent=selfChoice.emoji;opponentAnimal.textContent=opponentChoice.emoji;selfAnimalName.textContent=selfChoice.name;opponentAnimalName.textContent=opponentChoice.name}
function nextQuestion(){if(!latestGameState||latestGameState.status!=='playing'||disconnectHandled)return;const previous=currentQuestion?.prompt||'';currentQuestion=generateQuestion(previous);currentQuestion.choices=generateChoices(currentQuestion.answer);questionType.textContent=currentQuestion.label;battleQuestion.textContent=currentQuestion.prompt;battleFeedback.textContent='';battleFeedback.className='battle-feedback';renderChoices()}
function animateEvent(state){if(!state.last_event_id||state.last_event_id<=lastEventId)return;lastEventId=state.last_event_id;const eventSeat=Number(state.last_event_seat);const isHit=state.last_event_type==='hit';const eventFromSelf=eventSeat===Number(currentSeat);const attacker=eventFromSelf?selfAnimal:opponentAnimal;const target=isHit?(eventFromSelf?opponentAnimal:selfAnimal):attacker;attacker.classList.remove('attack');target.classList.remove('hit');void attacker.offsetWidth;attacker.classList.add('attack');if(isHit){const beam=eventFromSelf?laserLeft:laserRight;const sword=eventFromSelf?swordLeft:swordRight;setTimeout(()=>{if(disconnectHandled)return;beam.classList.remove('fire');void beam.offsetWidth;beam.classList.add('fire')},170);setTimeout(()=>{if(disconnectHandled)return;sword.classList.remove('slash');void sword.offsetWidth;sword.classList.add('slash')},300);setTimeout(()=>{target.classList.add('hit');techArena.classList.remove('screen-flash');void techArena.offsetWidth;techArena.classList.add('screen-flash')},360)}else{setTimeout(()=>target.classList.add('hit'),120)}}
function updateBattle(state){latestGameState=state;const view=makeBattleViewModel(state,currentSeat);selfName.textContent=view.self.name;opponentName.textContent=view.opponent.name;renderHearts(selfHp,view.self.hp);renderHearts(opponentHp,view.opponent.hp);selfScore.textContent=view.self.score;opponentScore.textContent=view.opponent.score;animateEvent(state);if(state.status==='finished')finishBattle(state)}
function startBattle(state){if(!battleStarted){battleStarted=true;matchedPlayer1.textContent=state.player1_name;matchedPlayer2.textContent=state.player2_name;setScreen('matched');setupAnimals();setTimeout(()=>{if(!currentRoomId)return;setScreen('battle');updateBattle(state);nextQuestion();handlePresenceSync()},650)}else{setScreen('battle');updateBattle(state)}}
function finishBattle(state){clearTimeout(opponentMissingTimer);opponentMissingTimer=null;document.querySelectorAll('.choice-btn').forEach(button=>button.disabled=true);battleStatusText.textContent='對戰結束';if(battleResult.classList.contains('show'))return;const won=Number(state.winner_seat)===Number(currentSeat);battleResult.classList.remove('victory','defeat');if(won){battleResultTitle.textContent=randomFrom(VICTORY_MESSAGES);battleResultText.textContent='太強了！按下按鈕回到大廳，再接受下一位挑戰者。';battleResult.classList.add('show','victory');launchPetalRain(5000)}else{battleResultTitle.textContent='💪 再戰一局！';battleResultText.textContent=randomFrom(DEFEAT_MESSAGES);battleResult.classList.add('show','defeat');clearPetalRain()}}
function handleGameState(state){if(!state||state.room_id!==currentRoomId)return;latestGameState=state;if(state.status==='playing')stopHostHeartbeat();if((state.status==='playing'||state.status==='finished')&&state.player1_name&&state.player2_name)startBattle(state)}
function renderChoices(){choiceGrid.textContent='';const letters=['A','B','C','D'];currentQuestion.choices.forEach((value,index)=>{const button=document.createElement('button');button.type='button';button.className='choice-btn';const badge=document.createElement('span');badge.className='choice-letter';badge.textContent=letters[index];button.append(badge,document.createTextNode(String(value)));button.addEventListener('click',()=>submitAnswer(value));choiceGrid.appendChild(button)})}
async function submitAnswer(answer){if(!currentQuestion||!latestGameState||latestGameState.status!=='playing'||disconnectHandled)return;const correct=answer===currentQuestion.answer;document.querySelectorAll('.choice-btn').forEach(button=>button.disabled=true);battleFeedback.textContent=correct?'✓ 答對！雷射＋大刀連段！':`✦ 再加油！正確答案是 ${currentQuestion.answer}`;battleFeedback.className=`battle-feedback ${correct?'good':'bad'}`;try{const{error}=await supabaseClient.rpc('resolve_answer',{p_room_id:currentRoomId,p_client_token:getClientToken(),p_is_correct:correct});if(error)throw error;setTimeout(()=>{battleFeedback.textContent='';nextQuestion()},680)}catch(error){battleFeedback.textContent=friendlyError(error,'答案送出失敗。');battleFeedback.className='battle-feedback bad';document.querySelectorAll('.choice-btn').forEach(button=>button.disabled=false)}}

function cancelWaitingRoomOnPageHide(){if(currentSeat!==1||currentScreen!=='waiting'||!currentRoomId)return;const payload=JSON.stringify({p_room_id:currentRoomId,p_client_token:getClientToken()});void fetch(`${SUPABASE_URL}/rest/v1/rpc/cancel_room`,{method:'POST',headers:{apikey:SUPABASE_PUBLISHABLE_KEY,'Content-Type':'application/json'},body:payload,keepalive:true}).catch(()=>{})}

nicknameForm.addEventListener('submit',async event=>{event.preventDefault();if(!supabaseClient){showMessage('Supabase 尚未連線完成，請稍候。','bad');return}const clean=normalizedNickname(nicknameInput.value);if(!nicknameIsValid(clean)){showMessage('暱稱請輸入 1～20 個字。','bad');nicknameInput.focus();return}nickname=clean;await enterLobby()});
refreshLobbyBtn.addEventListener('click',()=>loadLobby());createRoomBtn.addEventListener('click',()=>createRoom());cancelRoomBtn.addEventListener('click',()=>cancelCurrentRoom());battleReturnBtn.addEventListener('click',()=>enterLobby());
window.addEventListener('pagehide',cancelWaitingRoomOnPageHide);
window.addEventListener('online',()=>{setConnectionStatus('網路已恢復，正在同步…');if(currentScreen==='lobby')loadLobby();if(currentRoomId)fetchGameState(currentRoomId)});window.addEventListener('offline',()=>{setConnectionStatus('裝置目前離線','bad');showMessage('目前沒有網路連線，恢復網路後會再同步。','bad')});
async function initialize(){try{getClientToken();const{createClient}=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm');supabaseClient=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});setConnectionStatus('資料庫已連接','good');renderStartWelcome();enterLobbyBtn.disabled=false;enterLobbyBtn.textContent='進入遊戲大廳';nicknameInput.focus()}catch(error){console.error(error);setConnectionStatus('Supabase 載入失敗','bad');enterLobbyBtn.disabled=true;enterLobbyBtn.textContent='連線元件載入失敗';showMessage('無法載入 Supabase 元件，請確認網路正常後重新整理頁面。','bad')}}
initialize();
